<h1 class="text-center bg-primary"><label class="titulo">Editando Campeonato</label></h1>

<?php

    $form = $this->form;

    $form->setAttribute('action', $this->url('campeonato-admin', array('controller' => 'campeonato', 'action' => 'edit')));
    $form->setAttribute('class', "form-horizontal");

    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
?>
<div class="form-group">
    <div class="col-xs-12 col-md-6">
        <label for="nome">Nome</label>
        <?= $this->formRow($form->get('nome')); ?>
    </div>
</div>

<div class="form-group">
    <div class="col-xs-12 col-md-6">
        <label for="ano">Ano</label>
        <?= $this->formRow($form->get('ano')); ?>
    </div>
</div>

<div class="form-group">
    <div class="col-xs-12 col-md-6">
        <?= $this->formSubmit($form->get('submit')); ?>
    </div>
</div>

<?php
    echo $this->form()->closeTag();
?>